### ISSUE TITLE
Uncaught TypeError: Cannot read property '123' of undefined

### ISSUE THREAD

**Issue by garaboncias** [minodisk/js-refactor#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [js-refactor](https://github.com/minodisk/js-refactor) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property '123' of undefined

```
At /Users/radicsla/.atom/packages/js-refactor/lib/ripper.coffee:49

TypeError: Cannot read property '123' of undefined
  at Ripper.module.exports.Ripper.find (/Users/radicsla/.atom/packages/js-refactor/lib/ripper.coffee:49:21)
  at Watcher.module.exports.Watcher.rename (/Users/radicsla/.atom/packages/refactor/lib/watcher.coffee:150:22)
  at Main.module.exports.Main.onRename (/Users/radicsla/.atom/packages/refactor/lib/refactor.coffee:57:30)
  at atom-workspace.<anonymous> (/Users/radicsla/.atom/packages/refactor/lib/refactor.coffee:1:1)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:25.5 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 refactor:rename (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsformat"
    ],
    "projectHome": "/Users/radicsla/workspace"
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
docblockr, v0.5.8
highlight-selected, v0.7.0
js-refactor, v0.3.0
project-colorize, v0.1.0
project-manager, v1.14.1
refactor, v0.4.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by BlaM** [comment]
Got the same with 

    Cannot read property '1106' of undefined

 - and also identical to issue #12

(They all appear in ripper.coffee:49:21)
