### ISSUE TITLE
Failed to load the js-refactor package

### ISSUE THREAD

**Issue by damkraw** [minodisk/js-refactor#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [js-refactor](https://github.com/minodisk/js-refactor) package, v0.3.0

### Stack Trace

Failed to load the js-refactor package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/damian/.atom/packages/js-refactor/lib/notification_view.coffee:9:199)
    at /Users/damian/.atom/packages/js-refactor/lib/notification_view.coffee:14:5
    at Object.<anonymous> (/Users/damian/.atom/packages/js-refactor/lib/notification_view.coffee:80:5)
    at Object.<anonymous> (/Users/damian/.atom/packages/js-refactor/lib/notification_view.coffee:82:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-yaml",
      "minimap",
      "wrap-guide",
      "metrics",
      "language-toml",
      "language-mustache",
      "language-make",
      "open-on-github",
      "package-generator"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
color-picker, v1.7.0
js-refactor, v0.3.0
language-jsx, v0.1.4
layout-manager, v0.2.3
linter, v0.12.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
node-resolver, v1.0.1
npm-docs, v0.2.0
react, v0.11.6
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by tbusser** [comment]
I'm having the same issue since I've updated to Atom 0.198.0 this morning.

**Comment by kmdavis** [comment]
I'm also having this issue, since updating to Atom 0.207.0 this morning
